# Author:  Michael Jørgensen
#
# Description: Makefile for simulating the axi_pipe_wide.vhd file.

# List of source files
SRC += $(SRC_DIR)/axi_pipe_wide.vhd

# List of test specific simulation files
SRC += tb_axi_pipe_wide.vhd

# Top level entity
DUT = axi_pipe_wide

# Test duration
STOP_TIME = 10us

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

