# Author:  Michael Jørgensen
#
# Description: Makefile for simulating the axi_pipe_wide.vhd file.

# List of source files
SRC += $(SRC_DIR)/axis_remove_fixed_header.vhd
SRC += $(SRC_DIR)/axis_insert_fixed_header.vhd

# List of test specific simulation files
SRC += $(SIM_SRC_DIR)/lfsr.vhd
SRC += $(SIM_SRC_DIR)/random.vhd
SRC += $(SIM_SRC_DIR)/axi_fifo_sync.vhd
SRC += $(SIM_SRC_DIR)/axi_stim_verf.vhd
SRC += $(SIM_SRC_DIR)/axi_pause.vhd
SRC += tb_axis_fixed_header.vhd

# Top level entity
DUT = axis_fixed_header

# Test duration
STOP_TIME = 100us

# Test specific generics
GENERIC += -gG_PAUSE_SIZE=3
GENERIC += -gG_DEBUG=false
GENERIC += -gG_MAX_LENGTH=30
GENERIC += -gG_CNT_SIZE=14
GENERIC += -gG_FAST=true
GENERIC += -gG_RANDOM=true
GENERIC += -gG_DATA_BYTES=8
GENERIC += -gG_HEADER_BYTES=2

# Don't stop on errors
#ASSERT_LEVEL = none

include ../Makefile.inc

